db-uri = "postgres://ben@localhost:5433/warsync"
db-schemas = "public,warsync"
db-anon-role = "anon"
db-pool = 10
db-pool-acquisition-timeout = 10
server-host = "127.0.0.1"
server-port = 8767
log-level = "info"
openapi-mode = "ignore-privileges"
server-cors-allowed-origins = "*"
